version: "3.8"
services:
  app:
    build: .
    environment:
      BLOB_STORAGE_URL: http://blob-storage
      RABBITMQ_HOSTNAME: rabbitmq
      DIRECTORY_WITH_FFMPEG_AND_FFPROBE: "/usr/bin"
      POSTGRES_CONNECTION_STRING: "Host=postgres;Database=file_converter;Username=postgres;Password=postgres"
    depends_on:
      - rabbitmq
      - postgres
      - blob-storage
    restart: always
    ports:
      - "5001:80"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: file_converter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  blob-storage:
    image: gustavolim00/blob-storage:1.2
    ports:
      - "5000:80"
    environment:
      - BASE_FOLDER_PATH=/dados
      - APP_PORT=80
      - USE_CORS=true
    volumes:
      - /media/gustavo/8a393b51-8258-49ec-9f3d-d2a1d8764dbd/home/gustavo/blob-storage:/dados
